[package]
name = "chad_os"
version = "0.1.0"
authors = ["Ian-M-Moffett <spruiousvector@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
